// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVXZf-H1OCC7pSwe98ZP8Sqsu42N2kwZw',
    appId: '1:421429083575:web:d68ac34519acbe56f1fc32',
    messagingSenderId: '421429083575',
    projectId: 'picture-4d786',
    authDomain: 'picture-4d786.firebaseapp.com',
    storageBucket: 'picture-4d786.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaoC5kb9n8dO7bnQLXVjwUgbs63rvtuBI',
    appId: '1:421429083575:android:eca90ad8bcf5092cf1fc32',
    messagingSenderId: '421429083575',
    projectId: 'picture-4d786',
    storageBucket: 'picture-4d786.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWOhHnBs61EF2s8i1R9jnxAHgG-j0zcTc',
    appId: '1:421429083575:ios:a387847f2136ab5cf1fc32',
    messagingSenderId: '421429083575',
    projectId: 'picture-4d786',
    storageBucket: 'picture-4d786.appspot.com',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWOhHnBs61EF2s8i1R9jnxAHgG-j0zcTc',
    appId: '1:421429083575:ios:e3d0c239425b87c8f1fc32',
    messagingSenderId: '421429083575',
    projectId: 'picture-4d786',
    storageBucket: 'picture-4d786.appspot.com',
    iosBundleId: 'com.example.firestore.RunnerTests',
  );
}
